spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:101.35.18.131}:3306/hello_jwt
    username: root
    password: eMbq+sUWdy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#logging:
#  level:
#    root: debug