@startuml jwtFilter

|JwtAuthenticationFilter|
start
:获取请求首部;
if(首部不存在或首部不以"Bearer "开头?) is(yes) then
else (no)
|jwtService|
:提取首部;
if(token过期?) is(yes) then
|JwtAuthenticationFilter|
else (no)

endif
endif
:进入下一个过滤器;
stop;

@enduml